
    create table tb_cliente (
        id bigint generated by default as identity,
        cpf varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table tb_pagamento (
        quantidade_parcelas integer,
        status_pagamento tinyint check (status_pagamento between 0 and 2),
        valor_parcela float(53),
        id bigint generated by default as identity,
        "processo_id" bigint unique,
        primary key (id)
    );

    create table tb_parcela (
        data_parcela date,
        status_pagamento tinyint check (status_pagamento between 0 and 2),
        valor float(53),
        id bigint generated by default as identity,
        pagamento_id bigint,
        primary key (id)
    );

    create table tb_processo (
        data date,
        forma_pagamento tinyint check (forma_pagamento between 0 and 1),
        situação tinyint check (situação between 0 and 1),
        valor float(53),
        cliente_id bigint,
        id bigint generated by default as identity,
        descrição varchar(255),
        numero varchar(255),
        primary key (id)
    );

    alter table if exists tb_pagamento 
       add constraint FKlm49d6oihmhc8icb6t8eibirx 
       foreign key ("processo_id") 
       references tb_processo;

    alter table if exists tb_parcela 
       add constraint FKtbxmrdibyrqxsu2sjwk15lmhe 
       foreign key (pagamento_id) 
       references tb_pagamento;

    alter table if exists tb_processo 
       add constraint FKqnjsc3dvaju56icr91tpxqr9v 
       foreign key (cliente_id) 
       references tb_cliente;

    create table tb_cliente (
        id bigint generated by default as identity,
        cpf varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table tb_pagamento (
        quantidade_parcelas integer,
        status_pagamento tinyint check (status_pagamento between 0 and 2),
        valor_parcela float(53),
        id bigint generated by default as identity,
        "processo_id" bigint unique,
        primary key (id)
    );

    create table tb_parcela (
        data_parcela date,
        status_pagamento tinyint check (status_pagamento between 0 and 2),
        valor float(53),
        id bigint generated by default as identity,
        pagamento_id bigint,
        primary key (id)
    );

    create table tb_processo (
        data date,
        forma_pagamento tinyint check (forma_pagamento between 0 and 1),
        situação tinyint check (situação between 0 and 1),
        valor float(53),
        cliente_id bigint,
        id bigint generated by default as identity,
        descrição varchar(255),
        numero varchar(255),
        primary key (id)
    );

    alter table if exists tb_pagamento 
       add constraint FKlm49d6oihmhc8icb6t8eibirx 
       foreign key ("processo_id") 
       references tb_processo;

    alter table if exists tb_parcela 
       add constraint FKtbxmrdibyrqxsu2sjwk15lmhe 
       foreign key (pagamento_id) 
       references tb_pagamento;

    alter table if exists tb_processo 
       add constraint FKqnjsc3dvaju56icr91tpxqr9v 
       foreign key (cliente_id) 
       references tb_cliente;
